// Copies the Lucide icons Hallway uses into src/lib/icons.ts, so the app ships
// only these instead of all ~1,800. Run `bun run icons` after editing a list.
import { writeFileSync } from 'node:fs';

/** Icons for buttons and menus. The key is the name the app uses; the value is Lucide's name. */
const interfaceIcons = {
  'arrow-left': 'arrow-left',
  plus: 'plus',
  x: 'x',
  check: 'check',
  download: 'download',
  upload: 'upload',
  clock: 'clock',
  users: 'users',
  lock: 'lock',
  unlock: 'lock-open',
  pencil: 'pencil',
  'chevron-down': 'chevron-down',
  tablet: 'tablet',
  monitor: 'monitor',
  settings: 'settings',
  door: 'door-open',
  trash: 'trash',
  'alert-triangle': 'triangle-alert',
  'user-plus': 'user-plus',
  ellipsis: 'ellipsis',
  search: 'search',
  help: 'circle-question-mark',
  'arrow-right': 'arrow-right',
  'chevron-up': 'chevron-up',
  calendar: 'calendar-clock',
  copy: 'copy',
  ban: 'ban',
  'shield-check': 'shield-check',
  'circle-play': 'circle-play',
};

/** Icons a teacher can give a destination, in the groups the picker shows. */
const destinationGroups = {
  'Restroom & health': ['toilet', 'droplet', 'droplets', 'glass-water', 'bath', 'baby', 'stethoscope', 'pill', 'thermometer', 'heart-pulse', 'bandage', 'cross', 'accessibility'],
  'Offices & people': ['building', 'school', 'heart-handshake', 'user-round', 'users', 'contact', 'briefcase', 'clipboard-list', 'phone', 'mail', 'landmark', 'shield', 'badge-check'],
  'Learning': ['book-open', 'library', 'laptop', 'monitor', 'printer', 'pencil', 'notebook-pen', 'graduation-cap', 'flask-conical', 'microscope', 'calculator', 'palette', 'music', 'drama', 'globe'],
  'Food & drink': ['utensils', 'coffee', 'apple', 'sandwich', 'cup-soda', 'cookie', 'milk'],
  'Activities & outside': ['dumbbell', 'trophy', 'volleyball', 'bike', 'footprints', 'trees', 'sun', 'armchair'],
  'Places & things': ['backpack', 'map-pin', 'door-open', 'key', 'package', 'car', 'bus', 'house', 'flag', 'star', 'bell', 'clock', 'recycle', 'trash', 'shirt', 'smartphone', 'wrench', 'brush', 'sparkles'],
};

async function svg(lucideName) {
  const node = (await import(`lucide/dist/esm/icons/${lucideName}.mjs`)).default;
  return node.map(([tag, attrs]) => `<${tag} ${Object.entries(attrs).map(([k, v]) => `${k}="${v}"`).join(' ')}/>`).join('');
}

const entries = new Map();
for (const [name, source] of Object.entries(interfaceIcons)) entries.set(name, await svg(source));
for (const names of Object.values(destinationGroups)) {
  for (const name of names) if (!entries.has(name)) entries.set(name, await svg(name));
}

const quote = (name) => (/^[a-z]+$/.test(name) ? name : `'${name}'`);
const out = `// Generated by scripts/generate-icons.mjs from Lucide (https://lucide.dev, ISC license).
// Don't edit by hand: change the lists in the script and run \`bun run icons\`.
export const icons = {
${[...entries].map(([name, body]) => `  ${quote(name)}: '${body}',`).join('\n')}
} as const;

export type IconName = keyof typeof icons;

/** The icons a teacher can give a destination, grouped for the picker. */
export const destinationIconGroups = ${JSON.stringify(destinationGroups, null, 2).replace(/"/g, "'")} as const satisfies Record<string, readonly IconName[]>;
`;
writeFileSync('src/lib/icons.ts', out);
console.log(`Wrote ${entries.size} icons to src/lib/icons.ts`);
